### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by kevinjonesevans** [chaddech/nlb#1]
Could you point me in the right direction to download your dataset? I found your paper where you reference this github repo, but am having difficulty navigating bisque cyverse.

Thanks!

**Comment by chaddech** [comment]
Hi Kevin,

My co-author Tyr who uploaded the images emailed me this response below
when I emailed him about this. Please let me know if this doesn't help
things.

Take care,
Chad

Yeah, CyVerse is nice for free storage but not very user-friendly. It's
changed since we uploaded and gotten even worse.

If they navigate to the link below, they should be able to access the
images without logging in:

https://bisque.cyverse.org/client_service/view?resource=
https://bisque.cyverse.org/data_service/00-4Vcp37UZhQmfcVzBQ2JBhk


On Tue, Sep 19, 2017 at 4:52 PM, Kevin Jones-Evans <notifications@github.com

**Comment by kevinjonesevans** [comment]
I think the link got mangled, but when I go to https://bisque.cyverse.org/client_service/view?resource=https://bisque.cyverse.org/data_service/00-4Vcp37UZhQmfcVzBQ2JBhk, that works.

Thanks!!
